conda_forge_output_validation: true
test_on_native_only: true
bot:
  abi_migration_branches:
  - 5.x
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
  - linux_64
  - osx_64
  - win_64
azure:
  store_build_artifacts: true
